# Generated by Django 4.2.7 on 2023-11-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_remove_producto_factura_factura_rtn_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='facturas',
        ),
        migrations.AddField(
            model_name='factura',
            name='productos',
            field=models.ManyToManyField(related_name='productos', to='facturas.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
