# Generated by Django 4.2.7 on 2023-11-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_remove_producto_facturas_factura_productos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='productos',
            field=models.ManyToManyField(to='facturas.producto'),
        ),
    ]
