# Generated by Django 4.2.7 on 2023-11-27 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0004_alter_factura_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='description',
        ),
    ]
