# Generated by Django 4.2.7 on 2023-11-27 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0006_alter_producto_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='url',
            new_name='img',
        ),
    ]
