# Generated by Django 4.2.7 on 2023-11-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0008_remove_factura_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_disponible',
            field=models.IntegerField(default=0),
        ),
    ]
