# Generated by Django 4.2.7 on 2023-11-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0009_producto_cantidad_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='sub_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total_pagar',
            field=models.IntegerField(default=0),
        ),
    ]
