# Generated by Django 4.2.7 on 2023-11-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0013_alter_factura_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='productos',
            field=models.CharField(max_length=1000),
        ),
    ]
