# Generated by Django 4.2.7 on 2023-11-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0014_alter_factura_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total_pagar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
